from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # ...existing code...
    path('frete/<int:frete_id>/atualizar-status/', views.atualizar_status_frete, name='atualizar_status_frete'),
    path('selecionar-origem/', views.selecionar_origem, name='selecionar_origem'),
    path('selecionar-destino/', views.selecionar_destino, name='selecionar_destino'),
    path('confirmar-frete/', views.confirmar_frete, name='confirmar_frete'),
    path('loja-info/<int:loja_id>/', views.loja_info, name='loja_info'),
    path('meus-fretes/', views.meus_fretes, name='meus_fretes'),
    path('meus-fretes/relatorio-excel/', views.meus_fretes_relatorio_excel, name='meus_fretes_relatorio_excel'),
    path('frete/<int:frete_id>/', views.frete_detalhe, name='frete_detalhe'),
    path('frete/<int:frete_id>/editar/', views.editar_frete, name='editar_frete'),
    path('frete/<int:frete_id>/cancelar/', views.cancelar_frete, name='cancelar_frete'),
    path('fretes-para-aprovacao/', views.fretes_para_aprovacao, name='fretes_para_aprovacao'),
    path('direcionar-frete-ajax/', views.direcionar_frete_ajax, name='direcionar_frete_ajax'),
    path('criar-transportadora-ajax/', views.criar_transportadora_ajax, name='criar_transportadora_ajax'),
    path('editar-transportadora-ajax/', views.editar_transportadora_ajax, name='editar_transportadora_ajax'),
    path('excluir-transportadora-ajax/', views.excluir_transportadora_ajax, name='excluir_transportadora_ajax'),
    path('gerenciar-transportadoras/', views.gerenciar_transportadoras, name='gerenciar_transportadoras'),
    path('aprovar-frete/<int:frete_id>/', views.aprovar_frete, name='aprovar_frete'),
    path('fretes-para-cotacao/', views.fretes_para_cotacao, name='fretes_para_cotacao'),
    path('cotar-frete/<int:cotacao_id>/', views.cotar_frete, name='cotar_frete'),
    path('cotacoes-historico-transportadora/', views.cotacoes_historico_transportadora, name='cotacoes_historico_transportadora'),
    path('cotacoes-historico-transportadora/excel/', views.cotacoes_historico_transportadora_excel, name='cotacoes_historico_transportadora_excel'),
    path('cotacoes-recebidas/', views.cotacoes_recebidas, name='cotacoes_recebidas'),
    path('aprovar-cotacao/<int:cotacao_id>/', views.aprovar_cotacao, name='aprovar_cotacao'),
    path('fretes-aprovados-gerente/', views.fretes_aprovados_gerente, name='fretes_aprovados_gerente'),
    path('fretes-aprovados-gerente/excel/', views.fretes_aprovados_gerente_excel, name='fretes_aprovados_gerente_excel'),
    path('gerenciar-usuarios/', views.gerenciar_usuarios, name='gerenciar_usuarios'),
    path('criar-usuario/', views.criar_usuario, name='criar_usuario'),
    path('editar-usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('excluir-usuario/<int:user_id>/', views.excluir_usuario, name='excluir_usuario'),
    path('login/', auth_views.LoginView.as_view(template_name='fretes/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name='logout'),
    path('health/', views.health_check, name='health_check'),
    path('', views.home, name='home'),
    path('solicitar-frete/', views.selecionar_origem, name='solicitar_frete'),
]
