# Generated by Django 5.2.5 on 2025-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0002_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cep',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='loja',
            name='regional',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
