# Generated by Django 5.2.5 on 2025-08-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0003_loja_cep_loja_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='volume',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
