# Generated by Django 5.2.5 on 2025-08-27 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0004_destino_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='horario_coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes_origem', to='fretes.loja'),
        ),
    ]
