# Generated by Django 5.2.5 on 2025-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0005_freterequest_horario_coleta_freterequest_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='loja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
