# Generated by Django 5.2.5 on 2025-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0006_destino_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
