# Generated by Django 5.2.5 on 2025-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0007_destino_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
