# Generated by Django 5.2.5 on 2025-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0008_destino_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freterequest',
            name='horario_coleta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
