# Generated by Django 5.2.5 on 2025-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0009_alter_freterequest_horario_coleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('cotacao_enviada', 'Cotação enviada'), ('finalizado', 'Finalizado')], default='pendente', max_length=30),
        ),
    ]
