# Generated by Django 4.2.7 on 2025-09-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0010_freterequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='observacoes_origem',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Coleta'),
        ),
    ]
