# Generated by Django 5.2.5 on 2025-09-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0011_freterequest_observacoes_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='anexo_destino',
            field=models.FileField(blank=True, help_text='Arquivo Excel ou PDF relacionado ao destino', null=True, upload_to='anexos/destino/', verbose_name='Anexo do Destino'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='anexo_origem',
            field=models.FileField(blank=True, help_text='Arquivo Excel ou PDF relacionado à origem', null=True, upload_to='anexos/origem/', verbose_name='Anexo da Origem'),
        ),
    ]
