# Generated by Django 5.2.5 on 2025-09-09 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0012_destino_anexo_destino_freterequest_anexo_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('limitado', 'Acesso Limitado - Apenas solicitar e ver lista'), ('completo', 'Acesso Completo - Pode editar e ver detalhes')], default='limitado', max_length=20, verbose_name='Tipo de Acesso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
