# Generated by Django 5.2.5 on 2025-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Pode ver todos os fretes de todos os usuários', verbose_name='Usuário Master'),
        ),
    ]
