# Generated by Django 5.2.5 on 2025-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0014_userprofile_is_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='data_entrega',
            field=models.DateTimeField(blank=True, help_text='Data e horário previstos para entrega', null=True, verbose_name='Data de Entrega'),
        ),
    ]
