# Generated by Django 5.2.5 on 2025-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0015_destino_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='tipo_veiculo',
            field=models.CharField(blank=True, choices=[('carreta', 'Carreta'), ('truck', 'Truck'), ('vuc', 'VUC'), ('toco', 'Toco'), ('3_4', '3/4'), ('van', 'Van')], help_text='Tipo de veículo necessário para o frete', max_length=10, null=True, verbose_name='Tipo de Veículo'),
        ),
    ]
