# Generated by Django 5.2.5 on 2025-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0016_freterequest_tipo_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='anexo_nota_fiscal',
            field=models.FileField(blank=True, help_text='Arquivo da nota fiscal (PDF, Excel)', null=True, upload_to='anexos/nota_fiscal/', verbose_name='Anexo da Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='nota_fiscal_emitida',
            field=models.BooleanField(default=False, help_text='Indica se a nota fiscal já foi emitida', verbose_name='Nota Fiscal Emitida'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='quem_paga_frete',
            field=models.CharField(blank=True, help_text='Loja responsável pelo pagamento do frete', max_length=100, null=True, verbose_name='Quem Paga o Frete'),
        ),
    ]
