# Generated by Django 5.2.5 on 2025-09-11 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0017_freterequest_anexo_nota_fiscal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='centro_custo',
            field=models.CharField(blank=True, help_text='Centro de custo aprovado para o frete', max_length=100, null=True, verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='justificativa_rejeicao',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da Rejeição'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='observacoes_aprovacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Aprovação'),
        ),
        migrations.AlterField(
            model_name='freterequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cotacao_enviada', 'Cotação enviada'), ('finalizado', 'Finalizado')], default='aguardando_aprovacao', max_length=30),
        ),
    ]
