# Generated by Django 5.2.5 on 2025-09-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0018_freterequest_aprovador_freterequest_centro_custo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='data_cotacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Cotação'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='motivo_rejeicao_transportadora',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição pela Transportadora'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='observacoes_cotacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Cotação'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='transportadora',
            field=models.ForeignKey(blank=True, help_text='Transportadora responsável pela cotação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes_cotados', to=settings.AUTH_USER_MODEL, verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='valor_ajudante',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado pelo ajudante', max_digits=10, null=True, verbose_name='Valor do Ajudante'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado pelo frete', max_digits=10, null=True, verbose_name='Valor do Frete'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='valor_pedagio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado pelo pedágio', max_digits=10, null=True, verbose_name='Valor do Pedágio'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soma total da cotação', max_digits=10, null=True, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('normal', 'Usuário Normal'), ('master', 'Usuário Master'), ('transportadora', 'Transportadora')], default='normal', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='freterequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('cotacao_enviada', 'Cotação Enviada'), ('cotacao_recebida', 'Cotação Recebida'), ('cotacao_aprovada', 'Cotação Aprovada'), ('rejeitado', 'Rejeitado'), ('rejeitado_transportadora', 'Rejeitado pela Transportadora'), ('finalizado', 'Finalizado')], default='pendente', max_length=30),
        ),
    ]
