# Generated by Django 5.2.5 on 2025-09-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0019_freterequest_data_cotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('master', 'Usuário Master'), ('gerente', 'Gerente'), ('solicitante', 'Solicitante'), ('transportadora', 'Transportadora')], default='solicitante', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
