# Generated by Django 5.2.5 on 2025-09-11 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0020_alter_userprofile_tipo_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Frete')),
                ('valor_pedagio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Pedágio')),
                ('valor_ajudante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Ajudante')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('rejeitada_transportadora', 'Rejeitada pela Transportadora')], default='pendente', max_length=30)),
                ('data_cotacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Cotação')),
                ('observacoes_cotacao', models.TextField(blank=True, null=True, verbose_name='Observações da Cotação')),
                ('motivo_rejeicao_transportadora', models.TextField(blank=True, null=True, verbose_name='Motivo da Rejeição pela Transportadora')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('observacoes_aprovacao', models.TextField(blank=True, null=True, verbose_name='Observações da Aprovação')),
                ('justificativa_rejeicao', models.TextField(blank=True, null=True, verbose_name='Justificativa da Rejeição')),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotacoes_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='fretes.freterequest')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
