# Generated by Django 5.2.5 on 2025-09-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0021_cotacaofrete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Cancelamento'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, help_text='Justificativa para o cancelamento do frete', null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Cancelou'),
        ),
        migrations.AlterField(
            model_name='freterequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('cotacao_enviada', 'Cotação Enviada'), ('cotacao_recebida', 'Cotação Recebida'), ('cotacao_aprovada', 'Cotação Aprovada'), ('rejeitado', 'Rejeitado'), ('rejeitado_transportadora', 'Rejeitado pela Transportadora'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendente', max_length=30),
        ),
    ]
