# Generated by Django 5.2.5 on 2025-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0022_freterequest_data_cancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freterequest',
            name='precisa_ajudante',
            field=models.BooleanField(default=False, help_text='Indica se o frete necessita de ajudante', verbose_name='Precisa de Ajudante'),
        ),
        migrations.AddField(
            model_name='freterequest',
            name='quantidade_ajudantes',
            field=models.PositiveIntegerField(default=0, help_text='Número de ajudantes necessários', verbose_name='Quantidade de Ajudantes'),
        ),
    ]
