# Generated by Django 5.2.5 on 2025-09-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0023_freterequest_precisa_ajudante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacaofrete',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes_feitas', to='fretes.transportadora'),
        ),
    ]
