# Generated by Django 5.2.5 on 2025-09-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0024_alter_cotacaofrete_transportadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transportadora',
            field=models.ForeignKey(blank=True, help_text='Transportadora associada ao usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fretes.transportadora', verbose_name='Transportadora'),
        ),
    ]
