# Generated by Django 5.2.5 on 2025-09-16 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0026_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='freterequest',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('cotacao_enviada', 'Cotação Enviada'), ('cotacao_recebida', 'Cotação Recebida'), ('cotacao_aprovada', 'Cotação Aprovada'), ('agendado', 'Agendado'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('rejeitado', 'Rejeitado'), ('rejeitado_transportadora', 'Rejeitado pela Transportadora'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='pendente', max_length=30),
        ),
        migrations.CreateModel(
            name='AgendamentoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(max_length=10, verbose_name='Placa do Veículo')),
                ('modelo_veiculo', models.CharField(max_length=100, verbose_name='Modelo do Veículo')),
                ('cor_veiculo', models.CharField(max_length=50, verbose_name='Cor do Veículo')),
                ('motorista_nome', models.CharField(max_length=100, verbose_name='Nome do Motorista')),
                ('motorista_cpf', models.CharField(max_length=14, verbose_name='CPF do Motorista')),
                ('motorista_telefone', models.CharField(max_length=20, verbose_name='Telefone do Motorista')),
                ('data_coleta', models.DateTimeField(verbose_name='Data/Hora da Coleta')),
                ('data_entrega_prevista', models.DateTimeField(verbose_name='Data/Hora Prevista de Entrega')),
                ('observacoes_agendamento', models.TextField(blank=True, null=True, verbose_name='Observações do Agendamento')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('frete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='fretes.freterequest')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fretes.transportadora')),
                ('usuario_agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('coleta_iniciada', 'Coleta Iniciada'), ('coleta_concluida', 'Coleta Concluída'), ('em_transito', 'Em Trânsito'), ('entregando', 'Entregando'), ('entregue', 'Entregue'), ('problema', 'Problema na Entrega'), ('cancelado', 'Cancelado')], max_length=20)),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('localizacao_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização Atual')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tipo_problema', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo do Problema')),
                ('descricao_problema', models.TextField(blank=True, null=True, verbose_name='Descrição do Problema')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='fretes.agendamentofrete')),
                ('usuario_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
