# Generated by Django 5.2.5 on 2025-09-16 20:07

from django.db import migrations, models


def migrate_tracking_status(apps, schema_editor):
    """Migra os status antigos para os novos status simplificados"""
    TrackingFrete = apps.get_model('fretes', 'TrackingFrete')
    
    # Mapeamento dos status antigos para os novos
    status_mapping = {
        'coleta_iniciada': 'em_transito',
        'coleta_concluida': 'em_transito', 
        'entregando': 'em_transito',
        'cancelado': 'problema',  # Cancelados viram problemas
    }
    
    # Atualizar registros com status que precisam ser migrados
    for tracking in TrackingFrete.objects.all():
        if tracking.status in status_mapping:
            tracking.status = status_mapping[tracking.status]
            tracking.save()


def reverse_migrate_tracking_status(apps, schema_editor):
    """Reverte a migração - não é possível reverter com precisão"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fretes', '0027_alter_freterequest_status_agendamentofrete_and_more'),
    ]

    operations = [
        # Primeiro migra os dados
        migrations.RunPython(migrate_tracking_status, reverse_migrate_tracking_status),
        
        # Depois altera o campo
        migrations.AlterField(
            model_name='trackingfrete',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('problema', 'Problema na Entrega')], max_length=20),
        ),
    ]
